# Generated by Django 2.1.2 on 2019-05-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furkan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_handsome', models.BooleanField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
